site_name: Stakater Cloud Orchestrator
docs_dir: content
site_url: https://docs.stakater.com/cloud-orchestrator/
repo_url: https://github.com/stakater/sco-docs
edit_uri: blob/main/content/
theme:
  favicon: assets/images/favicon.svg

strict: true
validation:
  links:
    anchors: warn

extra:
  version:
    provider: mike
    default: latest

nav:
  - index.md
  - changelog.md
  - eula.md